<?php

namespace Drupal\group_jsonapi\EventSubscriber;

use Drupal\Core\Routing\RouteSubscriberBase;
use Symfony\Component\Routing\RouteCollection;

/**
 * Replace access checks of group content creation JSON:API routes.
 */
class RoutesSubscriber extends RouteSubscriberBase {

  /**
   * {@inheritDoc}
   */
  protected function alterRoutes(RouteCollection $collection) {
    foreach ($collection->getIterator() as $name => $route) {
      // Alter routes generated by JSON:API and swap the access layer
      if (preg_match('/^jsonapi\.group_content--.*\.collection\.post$/', $name)) {
        if ($route->hasRequirement('_entity_create_access')) {
          $requirements = $route->getRequirements() + [
              '_group_jsonapi_content_create_access' => $route->getRequirement('_entity_create_access'),
            ];
          unset($requirements['_entity_create_access']);
          $route->setRequirements($requirements);
        }
      }
    }
  }
}
