<?php

/**
 * @file
 * Contains Drupal\group\group.module
 */

use Drupal\Core\Url;

/**
 * Implements hook_theme().
 */
function group_theme() {
  return array(
    /*'group' => array(
      'render element' => 'elements',
    ),*/
    'group_add_list' => array(
      'variables' => array('group_types' => NULL),
    ),
  );
}

/**
 * Prepares variables for list of available group type templates.
 *
 * Default template: group-add-list.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - group_types: An array of group types.
 *
 * @see group_add_page()
 */
function template_preprocess_group_add_list(&$variables) {
  $variables['types'] = array();

  if (!empty($variables['group_types'])) {
    foreach ($variables['group_types'] as $type) {
      $variables['types'][$type->id()] = array(
        'type' => $type->id(),
        'add_link' => \Drupal::l($type->label(), new Url('group.add', array('group_type' => $type->id()))),
        'description' => array(
          '#markup' => $type->getDescription(),
        ),
      );
    }
  }
}
