<?php

/**
 * @file
 * Enables Group functionality for the Node module.
 */

use Drupal\Core\Access\AccessResult;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Session\AccountInterface;
use Drupal\node\NodeInterface;
use Drupal\node\NodeTypeInterface;
use Drupal\Core\Url;

/**
 * Implements hook_ENTITY_TYPE_insert().
 */
function gnode_node_type_insert(NodeTypeInterface $node_type) {
  \Drupal::service('plugin.manager.group_content_enabler')->clearCachedDefinitions();
}

/**
 * Implements hook_entity_operation().
 */
function gnode_entity_operation(EntityInterface $entity) {
  $operations = [];

  if ($entity->getEntityTypeId() == 'group' && \Drupal::moduleHandler()->moduleExists('views')) {
    /** @var \Drupal\group\Entity\GroupInterface $entity */
    if ($entity->hasPermission('access group_node overview', \Drupal::currentUser())) {
      /** @var \Symfony\Component\Routing\RouterInterface $router */
      $router = \Drupal::service('router.no_access_checks');
      if ($router->getRouteCollection()->get('view.group_nodes.page_1') !== NULL) {
        $operations['nodes'] = [
          'title' => t('Nodes'),
          'weight' => 20,
          'url' => Url::fromRoute('view.group_nodes.page_1', ['group' => $entity->id()]),
        ];
      }
    }
  }

  return $operations;
}

/**
 * Implements hook_preprocess_HOOK().
 */
function gnode_preprocess_node(&$variables) {
  // See if we are rendering the node within a group scope.
  if ($variables['view_mode'] == 'full' && $variables['page'] === FALSE) {
    $route_match = \Drupal::routeMatch();
    if ($route_match->getRouteName() == 'entity.group_content.entity_view') {
      $page_group_content = $route_match->getParameter('group_content');
      $variables['page'] = $page_group_content->getEntity()->id() == $variables['node']->id();
    }
  }
}
