<?php

/**
 * @file
 * Helper module for the Group tests.
 */

use Drupal\user\UserInterface;

/**
 * Implements hook_ENTITY_TYPE_update().
 */
function group_test_user_update(UserInterface $user) {
  if ($user->getChangedTime() == 123456789) {
    $user->setChangedTime(530496000)->save();
  }
}

/**
 * Implements hook_entity_bundle_info().
 */
function group_test_entity_bundle_info() {
  $bundles = [];
  if (\Drupal::moduleHandler()->moduleExists('node')) {
    $bundles['group_config_wrapper']['node_type']['label'] = t('Node type');
  }
  return $bundles;
}
